#ifndef __MBEDTLS_CONFIG_READER_H__
#define __MBEDTLS_CONFIG_READER_H__

#if MBED_CONF_MBED_CLOUD_CLIENT
    #define MBEDTLS_AES_ROM_TABLES
    #define MBEDTLS_AES_C
    #define MBEDTLS_CIPHER_C
    
    #define MBEDTLS_SHA256_C
    #define MBEDTLS_MD_C
    #define MBEDTLS_GCM_C

    #define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
    #define MBEDTLS_ECDH_C
    #define MBEDTLS_ECP_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_ECDSA_C
    #define MBEDTLS_X509_CRT_PARSE_C
    
    #define MBEDTLS_X509_USE_C
    
    #define MBEDTLS_OID_C
    #define MBEDTLS_PK_PARSE_C

    #define MBEDTLS_PK_C

    #define MBEDTLS_ASN1_WRITE_C
    #define MBEDTLS_ASN1_PARSE_C

    #define MBEDTLS_ECP_DP_SECP256R1_ENABLED
    #define MBEDTLS_ECP_DP_SECP384R1_ENABLED
    #define MBEDTLS_ECP_DP_CURVE25519_ENABLED

    #define MBEDTLS_BASE64_C
    #define MBEDTLS_PEM_PARSE_C

    #define MBEDTLS_PK_C

    #define MBEDTLS_SSL_CACHE_C
#endif

#endif // __MBEDTLS_CONFIG_READER_H__